### ISSUE TITLE
Set Multiplier of intel "k" series CPU

### ISSUE THREAD

**Issue by nikitavedre** [YuHuanTin/CodeRepository_Public#1]
How I can set multiplier of intel CPU with Throttlestop?

**Comment by YuHuanTin** [comment]
> How I can set multiplier of intel CPU with Throttlestop?

If you are talking about the Throttlestop application, then I don't know how to set it
I extracted the disable turbo and C1E function on/off in Throttlestop

**Comment by nikitavedre** [comment]
How you extracted the disable turbo and C1E function on/off in Throttlestop?

**Comment by YuHuanTin** [comment]
> How you extracted the disable turbo and C1E function on/off in Throttlestop?

As you can see in the code, I used x86dbg to debug the DeviceIoControl function directly to get the parameters sent to the driver

**Comment by nikitavedre** [comment]
can you tell me where is x86dbg ?and how to use this?

**Comment by YuHuanTin** [comment]
> can you tell me where is x86dbg ?and how to use this?

[here](https://github.com/x64dbg/x64dbg)
And if you ask me how to learn to debug the program, then I am not very clear, because I have just learned a little, you can look for tutorials

**Comment by nikitavedre** [comment]
I want to debug FIVR function

**Comment by nikitavedre** [comment]
I want to debug FIVR function

**Comment by YuHuanTin** [comment]
> I want to debug FIVR function

I have not debugged this function, I think if you do not want to debug it should be called directly using Throttlestop indirectly instead of using the driver directly called over, or should directly change the bios

**Comment by nikitavedre** [comment]
How I can do that?

**Comment by YuHuanTin** [comment]
![image](https://user-images.githubusercontent.com/51024916/233977907-f9849f57-1e41-4c4b-9bbf-bb809b80aedc.png)

It's possible you'll have to manually adjust the voltage or other features yourself, but I don't, and it seems to cause problems like cpu overheating, so you can look up Throttlestop's information to adjust it.
If you want to adjust it via bios, you should check your motherboard's cpu-related settings
